platform:
  - x86
  - x64

configuration:
  - debug
  - release

environment:
  matrix:
    - DC: dmd
      DVersion: 2.078.0
    - DC: ldc
      DVersion: 1.7.0

matrix:
  exclude:
    - DC: dmd
      platform: x86
    - DC: dmd
      configuration: release

skip_tags: true

artifacts:
  - path: selery-hub-%selery_version%-windows-%lower_platform%.exe
    name: hub
  - path: selery-node-%selery_version%-windows-%lower_platform%.exe
    name: node
  - path: selery-%selery_version%-windows-%lower_platform%.exe
    name: default
  - path: selery-%selery_version%-windows-%lower_platform%.zip
    name: zip

deploy:
  - provider: GitHub
    tag: v$(selery_version)
    release: Selery $(selery_version)
    description: "$(release_notes)"
    auth_token:
      secure: ioKlisLYTQCnQTUDVHlgLw24mtQ2/uMlCOt4BPvioprrpHYROYCP1lR/oFER/EIB
    artifact: selery-%selery_version%-windows-%lower_platform%.zip
    force_update: true
    on:
      DC: ldc2
      configuration: release
      selery_build: 0

install:
  - ps: function SetUpDCompiler
        {
            if($env:platform -eq "x86"){
              $env:DConf = "m32";
              $env:lower_platform = "x86";
            }
            elseif($env:platform -eq "x64"){
              $env:DConf = "m64";
              $env:lower_platform = "x64";
            }
            if($env:DC -eq "dmd"){
              $env:toolchain = "msvc";
              $version = $env:DVersion;
              Invoke-WebRequest "http://downloads.dlang.org/releases/2.x/$($version)/dmd.$($version).windows.7z" -OutFile "c:\dmd.7z";
              echo "finished.";
              pushd c:\\;
              7z x dmd.7z > $null;
              popd;
            }
            elseif($env:DC -eq "ldc"){
              $env:toolchain = "msvc";
              $version = $env:DVersion;
              Invoke-WebRequest "https://github.com/ldc-developers/ldc/releases/download/v$($version)/ldc2-$($version)-windows-$($env:lower_platform).7z" -OutFile "c:\ldc.7z";
              echo "finished.";
              pushd c:\\;
              7z x ldc.7z > $null;
              mv ldc2-$($version)-windows-$($env:lower_platform) ldc2;
              popd;
            }
        }
  - ps: SetUpDCompiler
  - powershell -Command Invoke-WebRequest https://github.com/electron/rcedit/releases/download/v1.0.0/rcedit-x64.exe -OutFile rcedit.exe
  - powershell -Command Invoke-WebRequest http://code.dlang.org/files/dub-1.3.0-windows-x86.zip -OutFile dub.zip
  - 7z x dub.zip -odub > nul
  - set PATH=%CD%;%CD%\%binpath%;%CD%\dub;%PATH%
  - dub --version

before_build:
  - ps: if($env:platform -eq "x86"){
            $env:compilersetupargs = "x86";
            $env:Darch = "x86";
          }
        elseif($env:platform -eq "x64"){
            $env:compilersetupargs = "amd64";
            $env:Darch = "x86_64";
        }
  - ps : if($env:DC -eq "dmd"){
           $env:PATH += ";C:\dmd2\windows\bin;";
         }
         elseif($env:DC -eq "ldc"){
           $env:PATH += ";C:\ldc2\bin";
           $env:DC = "ldc2";
         }
  - ps: $env:compilersetup = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall";
  - '"%compilersetup%" %compilersetupargs%'
  - mkdir plugins

build_script:
  - dub build --arch=%Darch% --compiler=%DC% --build=%CONFIGURATION%
  - cd builder\init
  - dub build --arch=%Darch% --compiler=%DC% --build=%CONFIGURATION%
  - cd ..
  - selery-init --generate-files
  - set /p selery_version=<version.txt
  - set /p selery_build=<build.txt
  - set /p release_notes=<notes.txt
  - selery-init hub
  - dub build --arch=%Darch% --compiler=%DC% --build=%CONFIGURATION%
  - selery-init node
  - dub build --arch=%Darch% --compiler=%DC% --build=%CONFIGURATION%
  - selery-init default
  - dub build --arch=%Darch% --compiler=%DC% --build=%CONFIGURATION%
  - selery-init hub --portable
  - dub build --arch=%Darch% --compiler=%DC% --build=%CONFIGURATION%
  - selery-init node --portable
  - dub build --arch=%Darch% --compiler=%DC% --build=%CONFIGURATION%
  - selery-init default --portable
  - dub build --arch=%Darch% --compiler=%DC% --build=%CONFIGURATION%
  - cd ..

after_build:
  - rcedit selery-hub-%selery_version%.exe --set-version-string ProductName "Selery's hub"
  - rcedit selery-hub-%selery_version%.exe --set-version-string FileDescription "Selery's hub %selery_version%"
  - rcedit selery-hub-%selery_version%.exe --set-version-string OriginalFileName selery-hub-%selery_version%.exe
  - rcedit selery-hub-%selery_version%.exe --set-file-version %selery_version%.%selery_build%
  - rcedit selery-hub-%selery_version%.exe --set-product-version %selery_version%
  - rcedit selery-hub-%selery_version%.exe --set-icon assets\icons\hub.ico
  
  - rcedit selery-node-%selery_version%.exe --set-version-string ProductName "Selery's node"
  - rcedit selery-node-%selery_version%.exe --set-version-string FileDescription "Selery's node %selery_version%"
  - rcedit selery-node-%selery_version%.exe --set-version-string OriginalFileName selery-node-%selery_version%.exe
  - rcedit selery-node-%selery_version%.exe --set-file-version %selery_version%.%selery_build%
  - rcedit selery-node-%selery_version%.exe --set-product-version %selery_version%
  - rcedit selery-node-%selery_version%.exe --set-icon assets\icons\node.ico
  
  - rcedit selery-%selery_version%.exe --set-version-string ProductName "Selery"
  - rcedit selery-%selery_version%.exe --set-version-string FileDescription "Selery %selery_version%"
  - rcedit selery-%selery_version%.exe --set-version-string OriginalFileName selery-%selery_version%.exe
  - rcedit selery-%selery_version%.exe --set-file-version %selery_version%.%selery_build%
  - rcedit selery-%selery_version%.exe --set-product-version %selery_version%
  - rcedit selery-%selery_version%.exe --set-icon assets\icons\default.ico
  
  - 7z a selery-%selery_version%-windows-%lower_platform%.zip selery-hub-%selery_version%.exe selery-node-%selery_version%.exe selery-%selery_version%.exe
  
  - move selery-hub-%selery_version%.exe selery-hub-%selery-version%-windows-%lower_platform%.exe
  - move selery-node-%selery_version%.exe selery-node-%selery-version%-windows-%lower_platform%.exe
  - move selery-%selery_version%.exe selery-%selery-version%-windows-%lower_platform%.exe

test_script:
  - selery-hub --about
  - selery-node --about
  - selery --about
