language: d

d:
  - dmd
  - ldc

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx

script:
  - travis_wait 30 dub build --compiler=$DC --build=release
  - cd builder
  - dub build --single --compiler=$DC --build=release init.d
  - ./selery-init hub
  - travis_wait 30 dub build --compiler=$DC --build=release
  - ./selery-init node
  - travis_wait 30 dub build --compiler=$DC --build=release
  - ./selery-init default
  - travis_wait 30 dub build --compiler=$DC --build=release
  - ./selery-init portable
  - travis_wait 30 dub build --compiler=$DC --build=release
  - cd ..
  
after_success:
  - ./selery-hub --about
  - ./selery-node --about
  - ./selery-default --about

notifications:
  - email: false
