language: d

d:
  - dmd
  - ldc

os:
  - linux
  - osx
  
env:
  - CONFIG=debug
  - CONFIG=release

matrix:
  exclude:
    - d: dmd
      env: CONFIG=release
  allow_failures:
    - os: osx
      d: dmd

deploy:
  provider: releases
  api_key: $API_KEY
  file: "selery-${SELERY_VERSION}-${OS}-x86_64.zip"
  skip_cleanup: true
  on:
    tags: true
    d: ldc
    condition: "$CONFIG = release"

script:
  - dub build --compiler=$DC --build=$CONFIG
  - cd builder
  - dub build --single --compiler=$DC --build=$CONFIG init.d
  - ./selery-init --generate-files
  - SELERY_VERSION=$(<version.txt)
  - ./selery-init hub
  - dub build --compiler=$DC --build=$CONFIG
  - ./selery-init node
  - dub build --compiler=$DC --build=$CONFIG
  - ./selery-init default
  - dub build --compiler=$DC --build=$CONFIG
  - ./selery-init hub --portable
  - dub build --compiler=$DC --build=$CONFIG
  - ./selery-init node --portable
  - dub build --compiler=$DC --build=$CONFIG
  - ./selery-init default --portable
  - dub build --compiler=$DC --build=$CONFIG
  - cd ..

after_success:
  - zip "selery-${SELERY_VERSION}-${OS}-x86_64.zip" "selery-hub-${SELERY_VERSION}" "selery-node-${SELERY_VERSION}" "selery-${SELERY_VERSION}"
  - ./selery-hub --about
  - ./selery-node --about
  - ./selery --about

notifications:
  - email: false
