language: d

d:
  - dmd
  - ldc
  
env:
  - CONFIG=debug
  - CONFIG=release

os:
  - linux
  - osx

matrix:
  exclude:
    - d: dmd
      CONFIG: release
  allow_failures:
    - os: osx
      d: dmd

script:
  - dub build --compiler=$DC --build=$CONFIG
  - cd builder
  - dub build --single --compiler=$DC --build=$CONFIG init.d
  - ./selery-init hub
  - dub build --compiler=$DC --build=$CONFIG
  - ./selery-init node
  - dub build --compiler=$DC --build=$CONFIG
  - ./selery-init default
  - dub build --compiler=$DC --build=$CONFIG
  - ./selery-init portable
  - dub build --compiler=$DC --build=$CONFIG
  - cd ..
  
after_success:
  - ./selery-hub --about
  - ./selery-node --about
  - ./selery-default --about

notifications:
  - email: false
