language: d

matrix:
  include:
    - {os: linux, d: dmd, env: CONFIG=debug ARCH=x86_64}
    - {os: linux, d: ldc, env: CONFIG=debug ARCH=x86_64}
#    - {os: linux, d: ldc, env: CONFIG=debug ARCH=x86}
#    - {os: linux, d: ldc, env: CONFIG=debug ARCH=arm}
#    - {os: linux, d: ldc, env: CONFIG=debug ARCH=aarch64}
    - {os: linux, d: ldc, env: CONFIG=release ARCH=x86_64}
#    - {os: linux, d: ldc, env: CONFIG=release ARCH=x86}
#    - {os: linux, d: ldc, env: CONFIG=release ARCH=arm}
#    - {os: linux, d: ldc, env: CONFIG=release ARCH=aarch64}
    - {os: osx, d: dmd, env: CONFIG=debug ARCH=x86_64}
    - {os: osx, d: ldc, env: CONFIG=debug ARCH=x86_64}
    - {os: osx, d: ldc, env: CONFIG=release ARCH=x86_64}
  allow_failures:
    - os: osx
      d: dmd

addons:
  apt:
    packages:
      - gcc-multilib

deploy:
  provider: releases
  api_key: $API_KEY
  file: "selery-${SELERY_VERSION}-${TRAVIS_OS_NAME}-${ARCH}.tar.xz"
  skip_cleanup: true
  on:
    tags: true
    condition: $CONFIG == "release" && $DC == "ldc2"

before_install:
  - chmod +x build.sh
  - mkdir plugins
#  - git clone https://github.com/selery-plugins/rcon.git plugins/rcon
  - git clone https://github.com/selery-plugins/vanilla.git plugins/vanilla
#  - git clone https://github.com/selery-plugins/web-admin.git plugins/web-admin
  - git clone https://github.com/selery-plugins/web-view.git plugins/web-view

script:
  - ./build.sh -c $DC -a $ARCH $CONFIG hub
  - ./build.sh -c $DC -a $ARCH $CONFIG node
  - ./build.sh -c $DC -a $ARCH $CONFIG default

after_success:
  - ./selery-hub --about
  - ./selery-node --about
  - ./selery --about
  - cd builder/views
  - SELERY_VERSION=$(<version.txt)
  - cd ../..
  - rm -rf assets/icons
  - tar -cJf "selery-${SELERY_VERSION}-${TRAVIS_OS_NAME}-${ARCH}.tar.xz" LICENSE selery-hub selery-node selery assets/
  - curl -s https://gist.githubusercontent.com/Kripth/e570f715c27d0a345619e2ea881ed97d/raw/ > update.d
  - rdmd update.d
  
after_failure:
  - curl -s https://gist.githubusercontent.com/Kripth/e570f715c27d0a345619e2ea881ed97d/raw/ > update.d
  - rdmd update.d

notifications:
  - email: false
