language: d

d:
  - dmd
  - ldc

os:
  - linux
  - osx
  
env:
  global:
    - ARCH=x86_64
  matrix:
    - CONFIG=debug
    - CONFIG=release

matrix:
  exclude:
    - d: dmd
      env: CONFIG=release
    - d: dmd
      os: osx
  allow_failures:
    - os: osx
      d: dmd

deploy:
  provider: releases
  api_key: $API_KEY
  file: "selery-${SELERY_VERSION}-${TRAVIS_OS_NAME}-${ARCH}.tar.xz"
  skip_cleanup: true
  on:
    tags: true
    condition: $CONFIG == "release" && $DC == "ldc2"

before_install:
  - chmod +x build.sh

script:
  - ./build.sh -c $DC -a $ARCH $CONFIG hub
  - ./build.sh -c $DC -a $ARCH $CONFIG node
  - ./build.sh -c $DC -a $ARCH $CONFIG default
  - cd builder
  - ./selery-init --generate-files
  - SELERY_VERSION=$(<version.txt)
  - cd ..

after_success:
  - ./selery-hub --about
  - ./selery-node --about
  - ./selery --about
  - rm -rf assets/icons
  - tar -cJf "selery-${SELERY_VERSION}-${TRAVIS_OS_NAME}-${ARCH}.tar.xz" LICENSE selery-hub selery-node selery assets/
  
after_failure:

notifications:
  - email: false
