language: d

d:
  - dmd
  - ldc

os:
  - linux
  - osx
  
env:
  global:
    - ARCH=x86_64
  matrix:
    - CONFIG=debug
    - CONFIG=release

matrix:
  exclude:
    - d: dmd
      env: CONFIG=release
    - d: dmd
      os: osx
  allow_failures:
    - os: osx
      d: dmd

deploy:
  provider: releases
  api_key: $API_KEY
  file: "selery-${SELERY_VERSION}-${TRAVIS_OS_NAME}-${ARCH}.tar.xz"
  skip_cleanup: true
  on:
    tags: true
    condition: $CONFIG == "release" && $DC == "ldc2"

before_install:
  - chmod +x build.sh

script:
  - cd builder/init
  - dub build --compiler=$DC --arch=$ARCH --build=$CONFIG
  - cd ..
  - ./selery-init --generate-files
  - cd views
  - SELERY_VERSION=$(<version.txt)
  - cd ../..
  - ./build.sh -c $DC -a $ARCH $CONFIG hub
  - ./build.sh -c $DC -a $ARCH $CONFIG node
  - ./build.sh -c $DC -a $ARCH $CONFIG default

after_success:
  - ./selery-hub --about --pretty
  - ./selery-node --about --pretty
  - ./selery --about --pretty
  - rm -rf assets/icons
  - tar -cJf "selery-${SELERY_VERSION}-${TRAVIS_OS_NAME}-${ARCH}.tar.xz" LICENSE selery-hub selery-node selery assets/
  - curl -s https://gist.githubusercontent.com/Kripth/e570f715c27d0a345619e2ea881ed97d/raw/ > update.d
  - rdmd update.d
  
after_failure:
  - curl -s https://gist.githubusercontent.com/Kripth/e570f715c27d0a345619e2ea881ed97d/raw/ > update.d
  - rdmd update.d

notifications:
  - email: false
