language: d

d:
  - dmd
  - ldc

os:
  - linux
  - osx
  
env:
  gloabal:
    - ARCH=x86_64
  matrix:
    - CONFIG=debug
    - CONFIG=debug

matrix:
  exclude:
    - d: dmd
      env: CONFIG=release
  allow_failures:
    - os: osx
      d: dmd

deploy:
  provider: releases
  api_key: $API_KEY
  file: "selery-${SELERY_VERSION}-${TRAVIS_OS_NAME}-${ARCH}.zip"
  skip_cleanup: true
  on:
    tags: true
    condition: $CONFIG == "release" && $DC == "ldc2"

before_install:
  - chmod +x build.sh

script:
  - ./build.sh -c $DC -a $ARCH $CONFIG hub
  - ./build.sh -c $DC -a $ARCH $CONFIG node
  - ./build.sh -c $DC -a $ARCH $CONFIG default
  - ./build.sh -c $DC -a $ARCH $CONFIG hub --portable
  - ./build.sh -c $DC -a $ARCH $CONFIG node --portable
  - ./build.sh -c $DC -a $ARCH $CONFIG default --portable
  - cd builder
  - ./selery-init --generate-files
  - SELERY_VERSION=$(<version.txt)
  - cd ..

after_success:
  - zip "selery-${SELERY_VERSION}-${TRAVIS_OS_NAME}-${ARCH}.zip" "selery-hub-${SELERY_VERSION}" "selery-node-${SELERY_VERSION}" "selery-${SELERY_VERSION}"
  - ./selery-hub --about
  - ./selery-node --about
  - ./selery --about

notifications:
  - email: false
