platform:
  - x86
  - x64

configuration:
  - debug
  - release

environment:
  matrix:
    - DC: dmd
      DVersion: 2.078.0
    - DC: ldc
      DVersion: 1.6.0

matrix:
  exclude:
    - DC: dmd
      platform: x86

skip_tags: true
branches:
  only:
    - master

artifacts:
  - path: selery-hub.exe
    name: hub
  - path: selery-node.exe
    name: node
  - path: selery-default.exe
    name: default
  - path: selery-%seleryversion%.exe
    name: portable

install:
  - ps: function SetUpDCompiler
        {
            if($env:platform -eq "x86"){
              $env:DConf = "m32";
              $env:Dmodel = "32";
            }
            elseif($env:platform -eq "x64"){
              $env:DConf = "m64";
              $env:Dmodel = "64";
            }
            if($env:DC -eq "dmd"){
              $env:toolchain = "msvc";
              $version = $env:DVersion;
              Invoke-WebRequest "http://downloads.dlang.org/releases/2.x/$($version)/dmd.$($version).windows.7z" -OutFile "c:\dmd.7z";
              echo "finished.";
              pushd c:\\;
              7z x dmd.7z > $null;
              popd;
            }
            elseif($env:DC -eq "ldc"){
              $env:toolchain = "msvc";
              $version = $env:DVersion;
              Invoke-WebRequest "https://github.com/ldc-developers/ldc/releases/download/v$($version)/ldc2-$($version)-win$($env:Dmodel)-msvc.zip" -OutFile "c:\ldc.zip";
              echo "finished.";
              pushd c:\\;
              7z x ldc.zip > $null;
              mv ldc2-$($version)-win$($env:DModel)-msvc ldc2;
              popd;
            }
        }
  - ps: SetUpDCompiler
  - powershell -Command Invoke-WebRequest https://github.com/electron/rcedit/releases/download/v1.0.0/rcedit-x64.exe -OutFile rcedit.exe
  - powershell -Command Invoke-WebRequest http://code.dlang.org/files/dub-1.3.0-windows-x86.zip -OutFile dub.zip
  - 7z x dub.zip -odub > nul
  - set PATH=%CD%;%CD%\%binpath%;%CD%\dub;%PATH%
  - dub --version

before_build:
  - ps: if($env:platform -eq "x86"){
            $env:compilersetupargs = "x86";
            $env:Darch = "x86";
            $env:Dmodel = "32";
          }
        elseif($env:platform -eq "x64"){
            $env:compilersetupargs = "amd64";
            $env:Darch = "x86_64";
            $env:Dmodel = "64";
        }
  - ps : if($env:DC -eq "dmd"){
           $env:PATH += ";C:\dmd2\windows\bin;";
         }
         elseif($env:DC -eq "ldc"){
           $env:PATH += ";C:\ldc2\bin";
           $env:DC = "ldc2";
         }
  - ps: $env:compilersetup = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall";
  - '"%compilersetup%" %compilersetupargs%'
  - mkdir plugins

build_script:
  - dub build --arch=%Darch% --compiler=%DC% --build=%CONFIGURATION%
  - cd builder
  - dub build --single --arch=%Darch% --compiler=%DC% --build=%CONFIGURATION% init.d
  - selery-init --version > version.txt
  - selery-init --full-version > fullversion.txt
  - set /p seleryversion=<version.txt
  - set /p seleryfullversion=<fullversion.txt
  - selery-init portable
  - dub build --arch=%Darch% --compiler=%DC% --build=%CONFIGURATION%
  - rcedit selery-%seleryversion%.exe --set-version-string ProductName Selery
  - rcedit selery-%seleryversion%.exe --set-version-string FileDescription "Selery %seleryversion%"
  - rcedit selery-%seleryversion%.exe --set-version-string OriginalFileName selery-%seleryversion%
  - rcedit selery-%seleryversion%.exe --set-file-version %seleryfullversion%
  - rcedit selery-%seleryversion%.exe --set-product-version %seleryversion%
  - rcedit selery-%seleryversion%.exe --set-icon assets/icon.ico
  - selery-init hub
  - dub build --arch=%Darch% --compiler=%DC% --build=%CONFIGURATION%
  - selery-init node
  - dub build --arch=%Darch% --compiler=%DC% --build=%CONFIGURATION%
  - selery-init default
  - dub build --arch=%Darch% --compiler=%DC% --build=%CONFIGURATION%
  - cd ..

test_script:
  - selery-hub --about
  - selery-node --about
  - selery-default --about
